// 引用 iOS 原生平台 api
import { UIDevice } from "UIKit";

export default function getBatteryInfo():void {
	
	// 开启电量检测
	UIDevice.current.isBatteryMonitoringEnabled = true
	
	// 返回数据
    const res = {
        errMsg: "getBatteryInfo:ok",
        level: UIDevice.current.batteryLevel * 100,
        isCharging: UIDevice.current.batteryState == UIDevice.BatteryState.charging,
    };
    console.log(res)
}
